# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

name: "Prepare Agent"

description: "Prepare Agent"

defaults:
  run:
    shell: pwsh

runs:
  using: "composite"
  steps:
    # See https://brew.sh
    - name: Set up Homebrew
      id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@master

    - name: Force vendored Ruby on Catalina
      run: echo 'HOMEBREW_FORCE_VENDOR_RUBY=1' >> $GITHUB_ENV
      shell: pwsh

    - name: Cache Bundler RubyGems
      uses: actions/cache@v1
      with:
        path: ${{ steps.set-up-homebrew.outputs.gems-path }}
        key: ${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
        restore-keys: ${{ runner.os }}-rubygems-

    - name: Install Bundler RubyGems
      run: brew install-bundler-gems
      shell: pwsh
