# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

name: "Create PR"

description: "Create PR"

runs:
  using: "composite"
  steps:
      - name: (scheduled-auto-release) Create Pull Request
        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        id: cpr
        uses: peter-evans/create-pull-request@2b011faafdcbc9ceb11414d64d0573f37c774b04 # v4.2.3
        with:
          commit-message: "Update ${{ env.FORMULA_NAME}} formula to version ${{ env.NEW_FORMULA_VERSION }}"
          token: "${{ secrets.PR_PAT }}"
          committer: PwshBot <pwshbot@microsoft.com>
          author: PwshBot <pwshbot@microsoft.com>
          title: "Update ${{ env.FORMULA_NAME }} formula to version ${{ env.NEW_FORMULA_VERSION }}"
          base: master
          draft: false
          branch: powershell-${{ env.CHANNEL_NAME }}-patch
          push-to-fork: pwshBot/Homebrew-Tap