# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

name: PowerShell daily scheduled update

permissions: read-all

on:
  workflow_dispatch:
  schedule:
    # At 20:20 UTC on every day-of-week from Monday through Friday.
    - cron:  '0 0 * * 1'

defaults:
  run:
    shell: pwsh -l -command ". '{0}'"

env:
  FORMULA_PATH: ./Formula/powershell-daily.rb
  UPDATE_SCRIPT_PATH: ./scripts/Upgrade-Formula.ps1
  FORMULA_NAME: powershell-daily
  CHANNEL_NAME: daily
  HOMEBREW_NO_ENV_HINTS: 1
  HOMEBREW_NO_INSTALL_CLEANUP: 1

jobs:
  homebrew-formula-daily:
    timeout-minutes: 15
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare Agent
        uses: ./.github/workflows/composite/prep

      - name: Install and Test Formula
        uses: ./.github/workflows/composite/installAndTest

      - name: Create PR if needed
        uses: ./.github/workflows/composite/createPR
        with:
          token: ${{ secrets.PR_PAT }}
        
