# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

name: PowerShell preview PR

permissions: read-all

on:
  push:
    paths:
      - '.github/workflows/powershell-preview.yml'
      - 'Formula/powershell-preview.rb'
    branches:
      - master
  pull_request:
    paths:
      - '.github/workflows/powershell-preview.yml'
      - 'Formula/powershell-preview.rb'

defaults:
  run:
    shell: pwsh
env:
  FORMULA_PATH: ./Formula/powershell-preview.rb
  UPDATE_SCRIPT_PATH: ./scripts/Upgrade-Formula.ps1
  FORMULA_NAME: powershell-preview
  CHANNEL_NAME: preview
  HOMEBREW_NO_ENV_HINTS: 1
  HOMEBREW_NO_INSTALL_CLEANUP: 1

jobs:
  homebrew-formula-preview:
    timeout-minutes: 15
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare Agent
        uses: ./.github/workflows/composite/prep

      - name: Install and Test Formula
        uses: ./.github/workflows/composite/installAndTest

      - name: Create PR if needed
        uses: ./.github/workflows/composite/createPR
