# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

name: PowerShell preview Formula
on:
  push:
    paths:
      - '.github/workflows/powershell-preview.yml'
      - 'Formula/powershell-preview.rb'
    branches:
      - master
  pull_request:
    paths:
      - '.github/workflows/powershell-preview.yml'
      - 'Formula/powershell-preview.rb'
  schedule:
    # At 20:20 UTC on every day-of-week from Monday through Friday.
    - cron:  '0 0/3 * * *'
defaults:
  run:
    shell: pwsh
env:
  FORMULA_PATH: ./Formula/powershell-preview.rb
  UPDATE_SCRIPT_PATH: ./scripts/Upgrade-Formula.ps1
  FORMULA_NAME: powershell-preview
  CHANNEL_NAME: preview
jobs:
  homebrew-formula-preview:
    timeout-minutes: 15
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # See https://brew.sh
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Force vendored Ruby on Catalina
        run: echo 'HOMEBREW_FORCE_VENDOR_RUBY=1' >> $GITHUB_ENV

      - name: Cache Bundler RubyGems
        uses: actions/cache@v1
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ runner.os }}-rubygems-

      - name: Install Bundler RubyGems
        run: brew install-bundler-gems

      - name: (scheduled-auto-release) Auto-update formula
        if: github.event_name == 'schedule'
        run: |
          &$env:UPDATE_SCRIPT_PATH -FormulaPath $env:FORMULA_PATH -Channel $env:CHANNEL_NAME
      - name: brew install (Verify install of formula)
        shell: bash
        run: |
          brew install --verbose --build-from-source $FORMULA_PATH
      # See https://docs.brew.sh/Formula-Cookbook#audit-the-formula
      - name: brew style
        if: github.event_name != 'schedule'
        run: |
          brew style $env:FORMULA_PATH
      - name: brew audit (Audit formula)
        if: github.event_name != 'schedule'
        # we are hitting a bug with audit, when it's working remove || true
        run: |
          brew audit --strict --online --display-filename --display-cop-names $env:FORMULA_PATH || true
      # See https://docs.brew.sh/Formula-Cookbook#add-a-test-to-the-formula
      - name: brew test (Verify tests in formula)
        run: |
          brew test $env:FORMULA_PATH
      - name: (scheduled-auto-release) Create Pull Request
        if: github.event_name == 'schedule'
        id: cpr
        uses: peter-evans/create-pull-request@v3
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          commit-message: "Update ${{ env.FORMULA_NAME}} formula to version ${{ env.NEW_FORMULA_VERSION }}"
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          title: "Update ${{ env.FORMULA_NAME }} formula to version ${{ env.NEW_FORMULA_VERSION }}"
          assignees: travisez13
          reviewers: travisez13
          base: master
          draft: false
          branch: powershell-preview-patch-${{ env.BRANCH_POSTFIX }}
