# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

name: PowerShell Formula CI

permissions: read-all

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/powershell.yml'
      - 'Formula/powershell.rb'
    branches:
      - master
  pull_request:
    paths:
      - '.github/workflows/powershell.yml'
      - 'Formula/powershell.rb'

defaults:
  run:
    shell: pwsh

env:
  FORMULA_PATH: ./Formula/powershell.rb
  UPDATE_SCRIPT_PATH: ./scripts/Upgrade-Formula.ps1
  FORMULA_NAME: powershell
  CHANNEL_NAME: stable
  HOMEBREW_NO_ENV_HINTS: 1
  HOMEBREW_NO_INSTALL_CLEANUP: 1

jobs:
  homebrew-formula-stable:
    timeout-minutes: 15
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare Agent
        uses: ./.github/workflows/composite/prep

      - name: uninstall powershell
        shell: bash
        run: |
          cd /
          PKG_ID='com.microsoft.powershell'
          pkgutil --only-files --files ${PKG_ID} | awk '!/\.app/' | tr '\n' '\0' | xargs -n 1 -0 -p sudo rm
          sudo pkgutil --forget ${PKG_ID}

      - name: Install and Test Formula
        uses: ./.github/workflows/composite/installAndTest
