# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

name: PowerShell daily Formula

permissions: read-all

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/powershell-daily.yml'
      - 'Formula/powershell-daily.rb'
    branches:
      - master
  pull_request:
    paths:
      - '.github/workflows/powershell-daily.yml'
      - 'Formula/powershell-daily.rb'

defaults:
  run:
    shell: pwsh -l -command ". '{0}'"

env:
  FORMULA_PATH: ./Formula/powershell-daily.rb
  UPDATE_SCRIPT_PATH: ./scripts/Upgrade-Formula.ps1
  FORMULA_NAME: powershell-daily
  CHANNEL_NAME: daily
  HOMEBREW_NO_ENV_HINTS: 1
  HOMEBREW_NO_INSTALL_CLEANUP: 1

jobs:
  homebrew-formula-daily:
    timeout-minutes: 15
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare Agent
        uses: ./.github/workflows/composite/prep

      - name: Install and Test Formula
        uses: ./.github/workflows/composite/installAndTest
