# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

name: PowerShell daily Formula PR

permissions: read-all

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/PR-powershell-daily.yml'
      - 'Formula/powershell-daily.rb'
    branches:
      - master
  pull_request:

defaults:
  run:
    shell: pwsh -l -command ". '{0}'"

env:
  FORMULA_PATH: ./Formula/powershell-daily.rb
  UPDATE_SCRIPT_PATH: ./scripts/Upgrade-Formula.ps1
  FORMULA_NAME: powershell-daily
  CHANNEL_NAME: daily
  HOMEBREW_NO_ENV_HINTS: 1
  HOMEBREW_NO_INSTALL_CLEANUP: 1

jobs:
  homebrew-formula-daily:
    timeout-minutes: 15
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Check for applicable files
        uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50
        id: filter
        with:
          filters: |
            workflows:
              - .github/workflows/PR-powershell-daily.yml
              - Formula/powershell-daily.rb

      - name: Prepare Agent
        if: steps.filter.outputs.workflows == 'true'
        uses: ./.github/workflows/composite/prep

      - name: Install and Test Formula
        if: steps.filter.outputs.workflows == 'true'
        uses: ./.github/workflows/composite/installAndTest
